name: CI on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      shell: bash
      run: g++ -std=c++2a -Wall -Wextra -pedantic-errors -I . -o test src/test.cpp
    - name: run
      shell: bash
      run: ./test
