name: CI on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: setup g++-11
      shell: bash
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt install -y g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11
    - uses: actions/checkout@v2
    - name: build
      shell: bash
      run: g++-11 -std=c++2a -Wall -Wextra -pedantic-errors -I . -o test src/test.cpp
    - name: run
      shell: bash
      run: ./test
